import Header from "@/components/Header";
import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import SearchBox from "@/components/SearchBox";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* Header */}
          <Header />
          {/* NavBar */}
          <Navbar />
          {/* Search Box */}
          <SearchBox />
          {children}
        </Providers>
      </body>
    </html>
  );
}

// export const metadata = {
//   title: "Imdb",
//   description: "Generated by create next app",
// };
